import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="banner">
          <div className="navbar">
            <div className="social-links">
              <a
                href="https://www.linkedin.com/in/jackson-hamada-017241253/"
                target="_blank"
              >
                <img
                  src="/38669.png"
                  className="w-12 h-12 ml-5 cursor-pointer"
                />
              </a>

              <a href="https://github.com/Sauce-Log" target="_blank">
                <img
                  src="/github.png"
                  className="w-12 h-12 ml-5 cursor-pointer"
                />
              </a>
            </div>

            <ul>
              <li>
                <a href="index.html">Home</a>
              </li>
              <li>
                <a href="Projects.html">Projects</a>
              </li>
              <li>
                <a href="Berkeley.html">Berkeley</a>
              </li>
              <li>
                <a href="Contact.html">Contact</a>
              </li>
              <li>
                <a href="Resume.html">Resume</a>
              </li>
            </ul>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
